// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PokerPlanning.Infrastructure.Persistence;

#nullable disable

namespace PokerPlanning.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PokerPlanningDbContext))]
    [Migration("20260528123055_AddUsers")]
    partial class AddUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("poker")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PokerPlanning.Domain.Rooms.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("_moderatorIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("moderator_ids");

                    b.HasKey("Id");

                    b.ToTable("rooms", "poker");
                });

            modelBuilder.Entity("PokerPlanning.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("_logins")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("logins");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", "poker");
                });

            modelBuilder.Entity("PokerPlanning.Domain.Rooms.Room", b =>
                {
                    b.OwnsMany("PokerPlanning.Domain.Participants.Participant", "Participants", b1 =>
                        {
                            b1.Property<Guid>("room_id")
                                .HasColumnType("uuid");

                            b1.Property<int>("ordinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("ordinal"));

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("display_name");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("participant_id");

                            b1.Property<DateTimeOffset>("JoinedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("joined_at");

                            b1.Property<int>("Role")
                                .HasColumnType("integer")
                                .HasColumnName("role");

                            b1.HasKey("room_id", "ordinal");

                            b1.ToTable("room_participants", "poker");

                            b1.WithOwner()
                                .HasForeignKey("room_id");
                        });

                    b.OwnsMany("PokerPlanning.Domain.Rooms.CompletedRound", "History", b1 =>
                        {
                            b1.Property<Guid>("room_id")
                                .HasColumnType("uuid");

                            b1.Property<int>("ordinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("ordinal"));

                            b1.Property<DateTimeOffset>("EndedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ended_at");

                            b1.Property<string>("FinalEstimate")
                                .HasColumnType("text")
                                .HasColumnName("final_estimate");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("round_id");

                            b1.Property<DateTimeOffset>("StartedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("started_at");

                            b1.Property<string>("Title")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("title");

                            b1.Property<string>("_votes")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("votes");

                            b1.HasKey("room_id", "ordinal");

                            b1.ToTable("completed_rounds", "poker");

                            b1.WithOwner()
                                .HasForeignKey("room_id");
                        });

                    b.Navigation("History");

                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
